### ISSUE TITLE
Borrower and contract address visibility

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/node-lending#10]
While cancelling contracts with Crypto_Saiyan we discovered it was difficult to coordinate which nodes he was going to cancel while chatting on Discord.

The reason is, as lender, I was only able to see his borrower wallet address, not node contract address and he was only able to see the latter and not the former.

I think the easiest solution would to be to add this info to the contract details info screen

**Comment by Dev-JamesR** [comment]
Enhancement added in https://github.com/Ether1Project/node-lending/commit/e8819673f679a76d641f96d22f89bd5de95278b3
