### ISSUE TITLE
JavaScript error which happens because 1e+21 cannot be converted to bignumber

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/node-lending#11]
Reported by Discord user @marjan

> hello! i found a bug in staking client app... the lender set 1000 ETHO fee, and when I'm trying to sign transaction there is an javascript error which happens because 1e+21 cannot be converted to bignumber. would need some help on this, to sign transaction and start staking ...
> the error happens in toBN function which depends on number-to-bn library

![image](https://user-images.githubusercontent.com/36507842/76851568-db418300-681f-11ea-92bb-e9468976b816.png)

**Comment by Dev-JamesR** [comment]
Fixed on https://github.com/Ether1Project/node-lending/commit/7e95a28e6a102d97dd4c12968c3ef77665e44315
