### ISSUE TITLE
Unable to execute smartcontract verification transaction

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/node-lending#12]
A user's verification transaction fails and reverts.

Here's a video showing the problem: [https://xn--kevin-kck-67a.de/s/SnJoeJyz4H7pgdC](https://xn--kevin-kck-67a.de/s/SnJoeJyz4H7pgdC)

**Comment by Dev-JamesR** [comment]
This is a fail-safe feature so you do not drain the contract as it needs to use funds from the contract to cover gas fees. You have a limit of only a few verification txs before the contract sees it as a fraudulent attempt to drain funds. It looks like 7+ validation attempts were made. Try abandoning or using a different contract.
