### ISSUE TITLE
Display origination fee in Lender/Borrower contracts

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/node-lending#2]
![image](https://user-images.githubusercontent.com/36507842/70859611-9e928280-1ee4-11ea-80a8-f0f0665ec93a.png)

Display original origination fee paid by borrower

**Comment by Primate411** [comment]
If displaying it on the main screen is too cumbersome, putting in the Contract Details screen might be a great alternative.  The point being is we want lenders to be able to see what the Origination Fee was for their currently running contracts

**Comment by Dev-JamesR** [comment]
Origination Fee added on https://github.com/Ether1Project/node-lending/commit/3405508c44c94cfd180920859e60e83a5dc85197
